@echo off
cd /d "C:\Users\user\Documents\your-trip"
echo Removing index.lock...
del /f /q ".git\index.lock" 2>nul
echo Running git add...
git add -A
echo Committing...
git commit -m "fix: AppShell chat TS clean + blob FormData upload"
echo Pushing to github...
git push github main
echo Done!
pause
